INSERT INTO WORKPACKAGE(ID,TASK_CODE, TASK_DESCRIPTION) VALUES(1, 'T1','Check Tyre Pressure');
INSERT INTO WORKPACKAGE(ID,TASK_CODE, TASK_DESCRIPTION) VALUES(2, 'T2','Repair Wings');
INSERT INTO WORKPACKAGE(ID,TASK_CODE, TASK_DESCRIPTION) VALUES(3, 'T3','Repair Brakes');
